import { rootStore } from "./RootStore";

export { rootStore };
export { AuthStore } from "./AuthStoreImpl";
export { UserStore } from "./UserStore";
export { BranchStore } from "./BranchStore";
export { ProgramStore } from "./ProgramStore";
export { ClassStore } from "./ClassStore";
export { LevelStore } from "./LevelStore";
export { ChargeFeeStore } from "./ChargeFeeStore";
export { StudentStore } from "./StudentStore";
export { AccountStore } from "./AccountStore";
export { ReportStore } from "./ReportStore";
export { AttendanceStore } from "./AttendanceStore";
export { InvoiceStore } from "./InvoiceStore";
export { VoucherStore } from "./VoucherStore";
export { LogStore } from "./LogStore";

export const authStore = rootStore.authStore;
export const userStore = rootStore.userStore;
export const branchStore = rootStore.branchStore;
export const programStore = rootStore.programStore;
export const classStore = rootStore.classStore;
export const levelStore = rootStore.levelStore;
export const chargeFeeStore = rootStore.chargeFeeStore;
export const studentStore = rootStore.studentStore;
export const accountStore = rootStore.accountStore;
export const reportStore = rootStore.reportStore;
export const attendanceStore = rootStore.attendanceStore;
export const invoiceStore = rootStore.invoiceStore;
export const voucherStore = rootStore.voucherStore;
export const logStore = rootStore.logStore;
